version: '3'
services:
  web:
    build: .
    image: rose_${EGG_SERVER_ENV}_web:${webTag}
    container_name: rose_${EGG_SERVER_ENV}_web
    ports:
      - ${webPort}:3000
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
  redis:
    image: "redis:alpine"
    container_name: rose_${EGG_SERVER_ENV}_redis
  db:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    container_name: rose_${EGG_SERVER_ENV}_db
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: ${database}
      MYSQL_ROOT_PASSWORD: ${mysqlPwd}
    volumes:
      - /Users/lww/roseData:/var/lib/mysql