version: '3'
services:
  rose_${env}_web:
    build: .
    image: rose_${env}_web:${webTag}
    container_name: rose_${env}_web
    ports:
      - ${webPort}:3000
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
  rose_${env}_redis:
    image: "redis:alpine"
    container_name: rose_${env}_redis
  rose_${env}_db:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    container_name: rose_${env}_db
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: ${database}
      MYSQL_ROOT_PASSWORD: ${mysqlPwd}